services:
  ark:
    image: diegoldente/ark-aio-server:latest
    container_name: ark-server
    restart: unless-stopped
    ports:
      - "7777:7777/udp"
      - "7778:7778/udp"
      - "27015:27015/udp"
      - "27020:27020/tcp"
    volumes:
      - ark_data:/ark
    environment:
      # --- General Server Settings ---
      - ARK_MAP=Fjordur
      - ARK_SESSION_NAME=My_ARK_Server
      - ARK_MAX_PLAYERS=10
      - ARK_SERVER_PASSWORD=yourpassword
      - ARK_ADMIN_PASSWORD=youradminpassword
      - ARK_PVE=False  
      
      # --- Difficulty Settings ---
      - ARK_DIFFICULTY_OFFSET=1.0
      - ARK_OVERRIDE_DIFFICULTY=5.0

      # --- Multipliers & Survival ---
      - ARK_XP_MULTIPLIER=2.0
      - ARK_TAMING_MULTIPLIER=5.0
      - ARK_HARVEST_MULTIPLIER=8.0
      - ARK_RES_RESPAWN=0.5
      - ARK_WATER_DRAIN=0.6
      - ARK_FOOD_DRAIN=0.6
      - ARK_HEALTH_RECOVERY=2.0
      - ARK_MATURE_SPEED=10.0
      - ARK_CUDDLE_INTERVAL=0.1
      
      # --- Gamma Fix ---
      # WICHTIG: PvE nutzt "Disable", PvP nutzt "Enable"!
      - ARK_GameUserSettings_ServerSettings_DisablePvEGamma=False
      - ARK_GameUserSettings_ServerSettings_EnablePvPGamma=True

volumes:
  ark_data:
